### ISSUE TITLE
Message details (payload) not rendered correctly when $ref is used in channels

### ISSUE THREAD

**Issue by AMulgrave** [asyncapi/vs-asyncapi-preview#204] opened 2024-01-11 05:22 UTC
[asyncapi.yaml.txt](https://github.com/asyncapi/vs-asyncapi-preview/files/13897525/asyncapi.yaml.txt)

Loading the yaml attachment into VS Code renders as follows:

![asyncapi preview render](https://github.com/asyncapi/vs-asyncapi-preview/assets/152357274/ad1f3839-8c9d-44a9-a989-d1b568d9881f)

Note the missing payload details for the channels messages using $ref.

While the same yaml renders correctly in Web Studio beta:

![Asyncapi Studio beta render](https://github.com/asyncapi/vs-asyncapi-preview/assets/152357274/58f42ad9-53e4-47a2-aec8-82ed37e18cde)

The rendering is also incomplete when the channels messsages are $ref to external asyncapi yaml files.

**Comment by ivangsa** [comment] 2024-01-11 15:11
Hi @AMulgrave 

thanks for taking the time to report this

You are right, this asyncapi.yml file renders alright in https://studio.asyncapi.com/ 
but it fails to render in vscode.

I will need to investigate further.

**Comment by ivangsa** [comment] 2024-01-19 12:15
Hi @AMulgrave 

we have investigates this issue, and we a reporting it to the react-component upstream...

Any way, you can simplify your asyncapi.yml definition without loosing any readability or reusability, for instance placing the `channels` section as first child (instead of inside `components`) would solve this rendering problem... I'm not sure what advantage you see in that indirection from channels -> component/channels

![image](https://github.com/asyncapi/vs-asyncapi-preview/assets/1246876/3aa36ec2-c9bf-46f0-ba5b-44fecd484d1d)

**Comment by ashmit-coder** [comment] 2024-01-19 15:33
HI @ivangsa , 
was working on the same issue and found the same cause.
Just wanted to ask if have you created a issue for it, If so could you please refrence it here.

In the case you haven't I would like to work towards it.

**Comment by ivangsa** [comment] 2024-01-19 16:35
@ashmit-coder please,  go ahead an create a PR!
Out of curiosity, if you can share the details of what it's about..

**Comment by ashmit-coder** [comment] 2024-01-19 16:51
> Out of curiosity, if you can share the details of what it's about..
sure i  wiill i need to look into to the working of the asycapi-react project. i will share my findings as soon as possible

**Comment by AMulgrave** [comment] 2024-01-21 19:41
> Hi @AMulgrave
> 
> we have investigates this issue, and we a reporting it to the react-component upstream...
> 
> Any way, you can simplify your asyncapi.yml definition without loosing any readability or reusability, for instance placing the `channels` section as first child (instead of inside `components`) would solve this rendering problem... I'm not sure what advantage you see in that indirection from channels -> component/channels
> 
> ![image](https://private-user-images.githubusercontent.com/1246876/298062057-3aa36ec2-c9bf-46f0-ba5b-44fecd484d1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NjYxMzgsIm5iZiI6MTcwNTg2NTgzOCwicGF0aCI6Ii8xMjQ2ODc2LzI5ODA2MjA1Ny0zYWEzNmVjMi1jOWJmLTQ2ZjAtYmE1Yi00NGZlY2Q0ODRkMWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjFUMTkzNzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDVhMjlmMWFmOTA2YThmODVlMWJhNWE3MWRjZjdhZWQ0ODQyY2I5ZGE2NDM4ZDY0ODQwMGU2MzI3MjMzMDU1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iDh52teF7hETkbFze_zAJMa8CQ_YM7cJe79lbXPQG0A)

This is just an example to show the issue from a single file. In my project the channel definitions are in an external file.

**Comment by ashmit-coder** [comment] 2024-01-26 12:46
> > Hi @AMulgrave
> > we have investigates this issue, and we a reporting it to the react-component upstream...
> > Any way, you can simplify your asyncapi.yml definition without loosing any readability or reusability, for instance placing the `channels` section as first child (instead of inside `components`) would solve this rendering problem... I'm not sure what advantage you see in that indirection from channels -> component/channels
> > ![image](https://private-user-images.githubusercontent.com/1246876/298062057-3aa36ec2-c9bf-46f0-ba5b-44fecd484d1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NjYxMzgsIm5iZiI6MTcwNTg2NTgzOCwicGF0aCI6Ii8xMjQ2ODc2LzI5ODA2MjA1Ny0zYWEzNmVjMi1jOWJmLTQ2ZjAtYmE1Yi00NGZlY2Q0ODRkMWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjFUMTkzNzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDVhMjlmMWFmOTA2YThmODVlMWJhNWE3MWRjZjdhZWQ0ODQyY2I5ZGE2NDM4ZDY0ODQwMGU2MzI3MjMzMDU1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iDh52teF7hETkbFze_zAJMa8CQ_YM7cJe79lbXPQG0A)
> 
> This is just an example to show the issue from a single file. In my project the channel definitions are in an external file.

Could you please provide aother image this one is not visible

**Comment by AMulgrave** [comment] 2024-01-28 19:52
In practice, I have the yaml structured that way to provide links to external yaml definitions. For simplicity, I provided the example to show the issue in one yaml file.

**Comment by aditygrg2** [comment] 2024-10-14 21:11
@ashmit-coder @ivangsa Have a look on this #240, if it is fine we can close this on both the repos.

**Comment by ivangsa** [comment] 2024-10-15 10:22
hi @aditygrg2, I'm not convinced of #240 

why it fixes the issue? what was causing the problem?

**Comment by aditygrg2** [comment] 2024-10-15 11:15
hello @ivangsa prefetching the complete text and using it as schema does not cause this problem, when fetched the order mattered, parsing happens synchronously top to bottom, if there are any references to a reference which are defined later, as in this case, it didn't worked

**Comment by ivangsa** [comment] 2024-10-15 13:32
so, how it works in the Studio... it's not using the same parser or react/component?

**Comment by aditygrg2** [comment] 2024-10-15 13:50
@ivangsa not much experience about the studio, but as I can see here it also passes in the complete content, instead of fetching 

https://github.com/asyncapi/studio/blob/40f287a2bfb30797e1e92c7e385a72ccb7870e27/apps/studio/src/services/parser.service.ts#L47C7-L47C101

**Comment by ivangsa** [comment] 2024-10-15 16:36
This is where the parsing of the schema is done in the react/component

https://github.com/asyncapi/asyncapi-react/blob/master/library/src/containers/AsyncApi/Standalone.tsx#L97-L98

I guess something is quite not right on the parsing for this not to work..

I think would be a better fix to understand the root cause before adventuring a fix..

**Comment by ivangsa** [comment] 2024-10-15 17:09
I dont like the idea of fixing something without understanding why...

I cant find where the standalone component parses the url, but if I do this on a separate project it seems that it resolves the channels :-/

```js
import { Parser, fromURL, stringify, unstringify } from "@asyncapi/parser";

const parser = new Parser();

const { document, diagnostics } = await fromURL(
  parser,
  "https://github.com/asyncapi/vs-asyncapi-preview/files/13897525/asyncapi.yaml.txt",
).parse();

// console.log(document, diagnostics);

console.log(stringify(document));
```

**Comment by ivangsa** [comment] 2024-10-15 17:10
@aditygrg2 are you willing to maintain (or even improve) this vscode extension?

**Comment by aditygrg2** [comment] 2024-10-15 17:15
@ivangsa 

> @aditygrg2 are you willing to maintain (or even improve) this vscode extension?

Yes, I would love to help!

**Closed** 2024-10-16 04:07 UTC
Labels: bug
